services:
    crontab-ui:
        container_name: crontab-ui
        image: alseambusher/crontab-ui
        restart: unless-stopped
        # user: "${UID:-1000}:${GID:-1000}"
        environment:
            TZ: "${TIMEZONE:-Europe/Warsaw}"
        # ports:
        #     - ${CRONTAB_UI_PORT:-8000}:8000
        hostname: "${DOMAIN:-crontab-ui.localhost}"
        networks:
            shared-network:
        volumes:
            - shared-home:/home/${APP_USER:-app}
        labels:
            # caddy: "${DOMAIN:-crontab-ui.localhost}"
            # caddy.reverse_proxy: "{{upstreams 8000}}"
            traefik.enable: "true"
            traefik.http.services.crontab-ui.loadbalancer.server.port: "8000"
            traefik.http.routers.crontab-ui.rule: "Host(`${DOMAIN:-crontab-ui.localhost}`)"
            traefik.http.routers.crontab-ui.entrypoints: "http"
            traefik.http.routers.crontab-ui.tls: "false"
            traefik.http.routers.crontab-ui.service: "crontab-ui"
            traefik.http.routers.crontab-ui-secure.rule: "Host(`${DOMAIN:-crontab-ui.localhost}`)"
            traefik.http.routers.crontab-ui-secure.entrypoints: "https"
            traefik.http.routers.crontab-ui-secure.tls: "true"
            traefik.http.routers.crontab-ui-secure.service: "crontab-ui"

networks:
    shared-network:
        name: ${SHARED_NETWORK_NAME:-shared-network}
        external: true

volumes:
    shared-home:
        name: ${SHARED_HOME_VOLUME:-shared-home}
        external: true
