services:
    backup:
        container_name: backup
        image: offen/docker-volume-backup
        restart: unless-stopped
        # user: "${UID:-1000}:${GID:-1000}"
        environment:
            TZ: "${TIMEZONE:-Europe/Warsaw}"
            BACKUP_CRON_EXPRESSION: "${BACKUP_CRON_EXPRESSION:-0 9,15,17,21 * * *}"
            BACKUP_FILENAME: "${BACKUP_FILENAME:-backup-%Y-%m-%dT%H-%M-%S.tar.gz}"
            BACKUP_LATEST_SYMLINK: "${BACKUP_LATEST_SYMLINK:-backup-latest.tar.gz}"
            BACKUP_PRUNING_PREFIX: "${BACKUP_PRUNING_PREFIX:-backup-}"
            BACKUP_RETENTION_DAYS: "${BACKUP_RETENTION_DAYS:-30}"
        networks:
            shared-network:
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - shared-home:/home/${APP_USER:-app}
            - ${BACKUP_DIR:-${HOME}/data/backups/docker/backup}:/archive

networks:
    shared-network:
        name: ${SHARED_NETWORK_NAME:-shared-network}
        external: true

volumes:
    shared-home:
        name: ${SHARED_HOME_VOLUME:-shared-home}
        external: true
