services:
    shared-home:
        container_name: shared-home
        image: alpine
        command: chown -R ${UID:-1000}:${GID:-1000} /home/${APP_USER:-app}
        restart: no
        user: root
        group_add:
            - ${GID:-1000}
        networks:
            shared-network:
        volumes:
            - shared-home:/home/${APP_USER:-app}

networks:
    shared-network:
        name: ${SHARED_NETWORK_NAME:-shared-network}
        external: true

volumes:
    shared-home:
        name: ${SHARED_HOME_VOLUME:-shared-home}
