services:
    mysql5:
        container_name: mysql5
        image: mysql:5
        restart: unless-stopped
        # user: "${UID:-1000}:${GID:-1000}"
        environment:
            TZ: "${TIMEZONE:-Europe/Warsaw}"
            MYSQL_DATABASE: "${DB_NAME:-default}"
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-secret}"
        ports:
            - ${DB_PORT:-3306}:3306
        networks:
            shared-network:
        volumes:
            - shared-home:/home/${APP_USER:-app}
            - mysql5-data:/var/lib/mysql
            - mysql5-conf:/etc/mysql
            - ./docker/mysql5/bin/backup.sh:/bin/backup.sh:ro
            - ${BACKUP_DIR:-${HOME}/data/backups/docker/mysql5}:/backup
        # labels:
        #     ofelia.enabled: "true"
        #     ofelia.job-exec.mysql5.command: "/bin/backup.sh"
        #     ofelia.job-exec.mysql5.schedule: "${BACKUP_CRON_EXPRESSION:-0 9,15,17,21 * * *}"

networks:
    shared-network:
        name: ${SHARED_NETWORK_NAME:-shared-network}
        external: true

volumes:
    shared-home:
        name: ${SHARED_HOME_VOLUME:-shared-home}
        external: true
    mysql5-data:
        name: mysql5-data
    mysql5-conf:
        name: mysql5-conf
